// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../geometry ../core/maybe ../core/urlUtils ../core/accessorSupport/decorators/property ../core/arrayUtils ../core/has ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/reader ../core/accessorSupport/decorators/subclass ./FeatureLayer ./graphics/sources/CSVSource ./graphics/sources/support/clientSideDefaults ../rest/support/Query ../chunks/persistableUrlUtils ../geometry/SpatialReference".split(" "),function(h,c,b,
r,t,e,z,A,B,u,v,w,n,x,k,p,y){b=function(m){function l(...a){a=m.call(this,...a)||this;a.capabilities=x.createCapabilities(!1,!1);a.delimiter=null;a.editingEnabled=!1;a.fields=null;a.latitudeField=null;a.locationType="coordinates";a.longitudeField=null;a.operationalLayerType="CSV";a.outFields=["*"];a.path=null;a.portalItem=null;a.spatialReference=y.WGS84;a.source=null;a.type="csv";return a}h._inheritsLoose(l,m);var g=l.prototype;g.normalizeCtorArgs=function(a,d){return"string"===typeof a?{url:a,...d}:
a};g.readWebMapLabelsVisible=function(a,d){return null!=d.showLabels?d.showLabels:!!(d.layerDefinition&&d.layerDefinition.drawingInfo&&d.layerDefinition.drawingInfo.labelingInfo)};g.createGraphicsSource=function(){var a=h._asyncToGenerator(function*(d){const f=new n({loadOptions:{delimiter:this.delimiter,fields:this.fields,latitudeField:this.latitudeField,longitudeField:this.longitudeField,spatialReference:this.spatialReference,timeInfo:this.timeInfo,url:this.url},customParameters:this.customParameters});
this._set("source",f);yield f.load({signal:d});this.read({locationInfo:f.locationInfo,columnDelimiter:f.delimiter},{origin:"service",url:this.parsedUrl});return f});return function(d){return a.apply(this,arguments)}}();g.queryFeatures=function(a,d){return this.load().then(()=>this.source.queryFeatures(k.from(a)||this.createQuery())).then(f=>{if(null!=f&&f.features)for(const q of f.features)q.layer=q.sourceLayer=this;return f})};g.queryObjectIds=function(a,d){return this.load().then(()=>this.source.queryObjectIds(k.from(a)||
this.createQuery()))};g.queryFeatureCount=function(a,d){return this.load().then(()=>this.source.queryFeatureCount(k.from(a)||this.createQuery()))};g.queryExtent=function(a,d){return this.load().then(()=>this.source.queryExtent(k.from(a)||this.createQuery()))};g.write=function(a,d){return m.prototype.write.call(this,a,{...d,writeLayerSchema:!0})};g.hasDataChanged=function(){var a=h._asyncToGenerator(function*(){try{const {dataChanged:d,updates:f}=yield this.source.refresh(this.customParameters);r.isSome(f)&&
this.read(f,{origin:"service",url:this.parsedUrl,ignoreDefaults:!0});return d}catch{}return!1});return function(){return a.apply(this,arguments)}}();g._verifyFields=function(){};g._verifySource=function(){};g._hasMemorySource=function(){return!1};h._createClass(l,[{key:"isTable",get:function(){return this.loaded&&null==this.geometryType}},{key:"url",set:function(a){a?(a=t.urlToObject(a),this._set("url",a.path),a.query&&(this.customParameters={...this.customParameters,...a.query})):this._set("url",
a)}}]);return l}(w);c.__decorate([e.property({readOnly:!0,json:{read:!1,write:!1}})],b.prototype,"capabilities",void 0);c.__decorate([e.property({type:[","," ",";","|","\t"],json:{read:{source:"columnDelimiter"},write:{target:"columnDelimiter",ignoreOrigin:!0}}})],b.prototype,"delimiter",void 0);c.__decorate([e.property({readOnly:!0,type:Boolean,json:{origins:{"web-scene":{read:!1,write:!1}}}})],b.prototype,"editingEnabled",void 0);c.__decorate([e.property({json:{read:{source:"layerDefinition.fields"},
write:{target:"layerDefinition.fields"}}})],b.prototype,"fields",void 0);c.__decorate([e.property({type:Boolean,readOnly:!0})],b.prototype,"isTable",null);c.__decorate([u.reader("web-map","labelsVisible",["layerDefinition.drawingInfo.labelingInfo","showLabels"])],b.prototype,"readWebMapLabelsVisible",null);c.__decorate([e.property({type:String,json:{read:{source:"locationInfo.latitudeFieldName"},write:{target:"locationInfo.latitudeFieldName",ignoreOrigin:!0}}})],b.prototype,"latitudeField",void 0);
c.__decorate([e.property({type:["show","hide"]})],b.prototype,"listMode",void 0);c.__decorate([e.property({type:["coordinates"],json:{read:{source:"locationInfo.locationType"},write:{target:"locationInfo.locationType",ignoreOrigin:!0,isRequired:!0}}})],b.prototype,"locationType",void 0);c.__decorate([e.property({type:String,json:{read:{source:"locationInfo.longitudeFieldName"},write:{target:"locationInfo.longitudeFieldName",ignoreOrigin:!0}}})],b.prototype,"longitudeField",void 0);c.__decorate([e.property({type:["CSV"]})],
b.prototype,"operationalLayerType",void 0);c.__decorate([e.property()],b.prototype,"outFields",void 0);c.__decorate([e.property({type:String,json:{origins:{"web-scene":{read:!1,write:!1}},read:!1,write:!1}})],b.prototype,"path",void 0);c.__decorate([e.property({json:{read:!1,write:!1,origins:{"web-document":{read:!1,write:!1}}}})],b.prototype,"portalItem",void 0);c.__decorate([e.property({json:{read:!1},cast:null,type:n,readOnly:!0})],b.prototype,"source",void 0);c.__decorate([e.property({json:{read:!1},
value:"csv",readOnly:!0})],b.prototype,"type",void 0);c.__decorate([e.property({json:{read:p.read,write:{isRequired:!0,ignoreOrigin:!0,writer:p.write}}})],b.prototype,"url",null);return b=c.__decorate([v.subclass("esri.layers.CSVLayer")],b)});