// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
require({cache:{"esri/renderers/support/heatmapUtils":function(){define(["exports","../../core/mathUtils"],function(m,t){function n(a,b,c,f,e){a=new Uint32Array(a*a);b="buffer"in b?b:new Float64Array(b);c="buffer"in c?new Uint32Array(c.buffer):new Uint32Array((new Uint8Array(c)).buffer);e=c.length/(e-f);for(let h=0;h<b.length;h++)a[h]=c[t.clamp(Math.floor((b[h]-f)*e),0,c.length-1)];return a.buffer}function p(a){const b=Math.round(3*a),c=2*a*a,f=new Float64Array(2*b+1);for(let e=0;e<=f.length;e++)f[e]=
Math.exp(-((e-b)**2)/c)/Math.sqrt(2*Math.PI)*(a/2);return f}function A(a,b){return"function"===typeof a?a:a?"string"===typeof b?c=>-1*+c[a]:c=>+c[a]+b:()=>1}function C(a,b){return null!=a?"string"===typeof b?c=>-1*+c.readAttribute(a):c=>+c.readAttribute(a)+b:c=>1}const F=(()=>{if(!("document"in globalThis))return()=>null;const a=document.createElement("canvas"),b=a.getContext("2d");a.height=512;a.width=1;return c=>{b.clearRect(0,0,1,a.height);const f=b.createLinearGradient(0,0,0,a.height);for(const {ratio:e,
color:h}of c.colorStops)f.addColorStop(Math.max(e,.001),`rgba(${h[0]}, ${h[1]}, ${h[2]}, ${h[3]})`);b.fillStyle=f;b.fillRect(0,0,1,a.height);return b.getImageData(0,0,1,a.height).data}})();m.calculateHeatmapIntensityInfo=function(a,b,c,f){const {blurRadius:e,fieldOffset:h,field:u}=b;b=new Float64Array(c*f);const l=p(e),d=Math.round(3*e);let g=Number.NEGATIVE_INFINITY;const v=A(u,h);for(const {geometry:k,attributes:q}of a){a=k.x-d;const w=k.y-d,G=Math.max(0,a);var r=Math.max(0,w);const D=Math.min(f,
k.y+d),E=Math.min(c,k.x+d),H=+v(q);for(let x=r;x<D;x++){const y=l[x-w];for(let z=G;z<E;z++)r=b[x*c+z]+=y*l[z-a]*H,r>g&&(g=r)}}return{matrix:b.buffer,max:g}};m.calculateHeatmapIntensityInfoReaders=function(a,b,c,f){const {blurRadius:e,fieldOffset:h,field:u}=b;b=new Float64Array(c*f);const l=p(e),d=Math.round(3*e);let g=Number.NEGATIVE_INFINITY;const v=C(u,h),r=new Set;for(const G of a)for(a=G.getCursor();a.next();){var k=a.getObjectId();if(r.has(k))continue;r.add(k);var q=a.readLegacyPointGeometry();
if(-128>q.x||q.x>=c+128||-128>q.y||q.y>f+128)continue;k=+v(a);const D=Math.round(q.x)-d,E=Math.round(q.y)-d,H=Math.max(0,D);var w=Math.max(0,E);const x=Math.min(f,Math.round(q.y)+d);q=Math.min(c,Math.round(q.x)+d);for(let y=w;y<x;y++){const z=l[y-E];for(let B=H;B<q;B++)w=b[y*c+B]+=z*l[B-D]*k,w>g&&(g=w)}}return{matrix:b.buffer,max:g}};m.createHeatmapImageData=n;m.createKernel=p;m.createValueFunction=A;m.createValueFunctionCursor=C;m.drawHeatmap=function(a,b,c,f,e,h){a.canvas.width=a.canvas.height=
b;a.clearRect(0,0,b,b);const u=a.getImageData(0,0,b,b);c&&f&&u.data.set(new Uint8ClampedArray(n(b,c,f,e,h)));a.putImageData(u,0,0)};m.generateGradient=F;Object.defineProperty(m,"__esModule",{value:!0})})},"esri/views/2d/layers/features/tileRenderers/BaseTileRenderer":function(){define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/HandleOwner ../../../../../core/accessorSupport/decorators/property ../../../../../core/arrayUtils ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/accessorSupport/decorators/subclass".split(" "),
function(m,t,n,p,A,C,F,a){n=function(b){function c(e){e=b.call(this,e)||this;e.tiles=new Map;return e}m._inheritsLoose(c,b);var f=c.prototype;f.destroy=function(){this.tiles.clear();this.layer=this.layerView=this.tileInfoView=this.tiles=null};f.acquireTile=function(e){const h=this.createTile(e);h.once("isReady",()=>this.notifyChange("updating"));this.tiles.set(e.id,h);return h};f.forceAttributeTextureUpload=function(){};f.forEachTile=function(e){this.tiles.forEach(e)};f.releaseTile=function(e){this.tiles.delete(e.key.id);
this.disposeTile(e)};f.isUpdating=function(){let e=!0;this.tiles.forEach(h=>{e=e&&h.isReady});return!e};f.setHighlight=function(){};f.invalidateLabels=function(){};f.requestUpdate=function(){this.layerView.requestUpdate()};m._createClass(c,[{key:"updating",get:function(){return this.isUpdating()}}]);return c}(n.HandleOwner);t.__decorate([p.property()],n.prototype,"layer",void 0);t.__decorate([p.property()],n.prototype,"layerView",void 0);t.__decorate([p.property()],n.prototype,"tileInfoView",void 0);
t.__decorate([p.property()],n.prototype,"updating",null);return n=t.__decorate([a.subclass("esri.views.2d.layers.features.tileRenderers.BaseTileRenderer")],n)})},"esri/views/2d/layers/features/tileRenderers/support/HeatmapSource":function(){define(["exports","../../../../../../renderers/support/heatmapUtils"],function(m,t){let n=function(){function p(){this.gradient=null;this.width=this.height=512}p.prototype.render=function(A){t.drawHeatmap(A,512,this.intensities,this.gradient,this.minPixelIntensity,
this.maxPixelIntensity)};return p}();m.HeatmapSource=n;Object.defineProperty(m,"__esModule",{value:!0})})},"*noref":1}});
define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/Logger ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/has ../../../../../core/accessorSupport/set ../../../../../core/accessorSupport/decorators/subclass ../../../../../renderers/support/heatmapUtils ../../../engine/BitmapTileContainer ./BaseTileRenderer ./support/HeatmapSource".split(" "),function(m,t,n,p,A,C,F,a,b,c,f,e){n=function(h){function u(d){var g=
h.call(this,d)||this;g._intensityInfo={minPixelIntensity:0,maxPixelIntensity:0};g.featuresView={attributeView:{initialize:()=>{},requestUpdate:()=>{}},requestRender:()=>{}};g._container=new c.BitmapTileContainer(d.tileInfoView);return g}m._inheritsLoose(u,h);var l=u.prototype;l.createTile=function(d){const g=this._container.createTile(d);this.tileInfoView.getTileCoords(g.bitmap,d);g.bitmap.resolution=this.tileInfoView.getTileResolution(d);return g};l.onConfigUpdate=function(){const d=this.layer.renderer;
if("heatmap"===d.type){const {minPixelIntensity:g,maxPixelIntensity:v}=d;this._intensityInfo.minPixelIntensity=g;this._intensityInfo.maxPixelIntensity=v;this._gradient=b.generateGradient(d.toJSON());this.tiles.forEach(r=>{const k=r.bitmap.source;k&&(k.minPixelIntensity=g,k.maxPixelIntensity=v,k.gradient=this._gradient,r.bitmap.invalidateTexture())})}};l.hitTest=function(){return Promise.resolve([])};l.install=function(d){d.addChild(this._container)};l.uninstall=function(d){this._container.removeAllChildren();
d.removeChild(this._container)};l.disposeTile=function(d){this._container.removeChild(d);d.destroy()};l.supportsRenderer=function(d){return d&&"heatmap"===d.type};l.onTileData=function(d){const g=this.tiles.get(d.tileKey);if(g){d=d.intensityInfo;var {minPixelIntensity:v,maxPixelIntensity:r}=this._intensityInfo,k=g.bitmap.source||new e.HeatmapSource;k.intensities=d&&d.matrix||null;k.minPixelIntensity=v;k.maxPixelIntensity=r;k.gradient=this._gradient;g.bitmap.source=k;this._container.addChild(g);this._container.requestRender();
this.requestUpdate()}};l.onTileError=function(d){console.error(d)};l.lockGPUUploads=function(){};l.unlockGPUUploads=function(){};l.fetchResource=function(d,g){console.error(d);return Promise.reject()};return u}(f);return n=t.__decorate([a.subclass("esri.views.2d.layers.features.tileRenderers.HeatmapTileRenderer")],n)});